config/routes.rb
Expenser::Application.routes.draw do
  get "welcome/index"

   root 'welcome#index'

resources :expenses

end

app/models/expense.rb
class Expense < ActiveRecord::Base
CATEGORIES = ['Meals', 'Car Rental', 'Gas']
CURRENCY = ['CAD', 'USD', 'EUR']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
def new
end

def show
@expense = Expense.find(params[:id])
end

def create
@expense = Expense.new(expense_params)
@expense.save
redirect_to @expense
end

private
  def expense_params
    params.require(:expense).permit(:category, :description, :amount, :currency)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/expenses/enter.html.erb
<h1>New Expense entry!</h1>

<%= form_for :expense, url: expenses_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/expenses/index.html.erb
<h1>Expenses listing</h1>
<table>
<tr>
<th>Category</th>
<th>Amount</th>
</tr>
<% expenses=Expense.all %>
<% expenses.each do |expense| %>
<tr>
<td><%=expense.category %></td>
<td><%=expense.amount %></td>
</tr>
<% end %>
<% if expenses.size == 0 %>
	<em>No Expenses Found</em>
</table>

app/views/expenses/init.html.erb
<% Expense = Hash.new $>
<%="this is shown from init" %>

app/views/expenses/new.html.erb
<h1>New Expense entry!</h1>

<%= form_for :expense, url: expenses_path do |f| %>
  <p>
    <%= f.label :category %><br>
	<%= f.collection_select :category, Expense::CATEGORIES, :to_s, :to_s, 
       :include_blank => false
	   %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  
  
    <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
	<%# amount=amount+2 %>
  </p>
  
    <p>
    <%= f.label :currency %><br>
    	<%= f.collection_select :currency, Expense::CURRENCY, :to_s, :to_s, 
       :include_blank => false
	   %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/expenses/show.html.erb
<p><%= "Expense number:" + @expense.id.to_s %></p>
<p><%= "Expense description:" + @expense.description.to_s %></p>
<p><%= "Expense amount:" + @expense.amount.number_to_currency(precision:2) %></p>
<p><%= "Expense currency:" + @expense.currency.to_s %></p>
<p><%= "Expense category:" + @expense.category %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head><title>Xpenser!</title></head>
<header><%= "You are currently using Xpenser!" %></header>
<body>
<%# expense = Expense.find(1) %>
<h1><%= yield %></h1>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Expenser</h1>